name: PR to main from release merged
on:
  push:
    branches:
      - release
jobs:
  autoPRMainFromRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset release branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "chore: Auto PR to Main from Release Merged"
          branch: release

