name: Prepare release branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: true
      base:
        description: 'base version'
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create release and Generate release note
        uses: nextDriveIoE/release-note-generator-action@master
        with:
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          jira_url: 'https://nextdrive.atlassian.net'
          jira_project: 'EC,AT,EIS,IOE,RD,AP,IOEP,NEB'
          jira_user: ${{ secrets.JIRA_USER }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          base_version: ${{ github.event.inputs.base }}
          current_version: ${{ github.event.inputs.version }}
