name: Run Unit Test

on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'feature/*'
      - 'fix/*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[SKIP CI]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: 18
        registry-url: 'https://oanexus.nextdrive.io/repository/npm-registry/'
        scope: '@nextdrive'
    - name: run test
      run: |
        npm install
        npm run test
      env:
        CI: true
        ELASTIC_APM_ACTIVE: false
